### ISSUE TITLE
gtk2 version?

### ISSUE THREAD

**Issue by orbea** [jgke/connman-gtk#22]
Is it possible there could be an optional gtk2 version of connman-gtk? I personally much prefer how gtk2 looks and additionally all my favorite themes are gtk2 only so while your program is useful, it will never look right for me...

**Comment by jgke** [comment]
No. I have no interest of maintaining a branch that would support a long-(semi-)deprecated version of GTK. Besides, including support for GTK2 would severely worsen the code quality across the whole project due to several changes in GTK3. I would suggest for you to find a new favourite theme that works with GTK3.

That being said, in the end there aren't that many changes that would be needed to be done for GTK2 support (replace GtkApplication with whatever it's in GTK2, replace GtkGrid, some minor tweaks), but I won't be merging the changes to my tree.
